[package]
name = "gddb"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lib_gddb = { git = "https://github.com/gregates/lib-gddb.git", branch = "mainline" }
